text_one = str(input())
print(text_one[2])
print(text_one[-2])
print(text_one[0:5])
print(text_one[0:-2])
print(text_one[0::2])
print(text_one[1::2])
print(text_one[::-1])
print(text_one[::-2])
print(len(text_one))
